bookAbbreviation = {'Deuteronomy': 'Deut',
'Acts': 'Acts',
'Habacuc': 'Hab',
'Daniel': 'Dan',
'Jonah': 'Jon',
'Wisdom': 'Wis',
'Aggeus': 'Hag',
'Ezechiel': 'Ezek',
'Habakkuk': 'Hab',
'Canticles': 'Song',
'Song of Solomon': 'Song',
'2 John': '2 Jn',
'Malachias': 'Mal',
'Letter of Jeremiah': 'Lam',
'Baruch': 'Bar',
'Psalms': 'Ps',
'James': 'Jas',
'Titus': 'Tit',
'Hosea': 'Hos',
'Joshua': 'Josh',
'Hebrews': 'Heb',
'Ezekiel': 'Ezek',
'Prayer of Azariah': 'Az',
'Philemon': 'Philem',
'Bel and the Dragon': 'Bel',
'2 Maccabees': '2 Mac',
'Micah': 'Mic',
'3 John': '3 Jn',
'1 Kings': '1 Sam',
'Mark': 'Mk',
'Matthew': 'Mt',
'1 Thessalonians': '1 Thess',
'2 Peter': '1 Pet',
'Malachi': 'Mal',
'Colossians': 'Col',
'John': 'Jn',
'2 Paralipomenon': '2 Chron',
'Isaias': 'Is',
'Obadiah': 'Obad',
'Prologue to Wisdom of Jesus Son of Sirach': 'Sir',
'Ephesians': 'Eph',
'1 Maccabees': '1 Mac',
'Galatians': 'Gal',
'Genesis': 'Gen',
'Job': 'Job',
'Jonas': 'Jon',
'Isaiah': 'Is',
'Proverbs': 'Prov',
'Leviticus': 'Lev',
'2 Esdras': 'Neh',
'Zephaniah': 'Zeph',
'Abdias': 'Obad',
'Jude': 'Jude',
'Haggai': 'Hag',
'Amos': 'Amos',
'Osee': 'Hos',
'Jeremiah': 'Jer',
'Ezra': 'Ezra',
'Acts of Apostles': 'Acts',
'Judith': 'Jud',
'2 Machabees': '2 Mac',
'Philippians': 'Phil',
'Sophonias': 'Zeph',
'Tobit': 'Tob',
'Ruth': 'Ruth',
'1 Esdras': 'Ezra',
'2 Samuel': '2 Sam',
'Exodus': 'Ex',
'1 Paralipomenon': '1 Chron',
'Wisdom of Jesus Son of Sirach': 'Sir',
'Romans': 'Rom',
'2 Timothy': '2 Tim',
'Jeremias': 'Jer',
'4 Kings': '2 Kings',
'Micheas': 'Mic',
'Nahum': 'Nahum',
'Zechariah': 'Zech',
'Lamentations': 'Lam',
'Apocalypse': 'Rev',
'Tobias': 'Tob',
'Wisdom of Solomon': 'Prov',
'Baruch': 'Bar',
'Numbers': 'Num',
'2 Corinthians': '2 Cor',
'1 Machabees': '1 Mac',
'Judges': 'Judg',
'Revelation': 'Rev',
'3 Kings': '1 Kings',
'Susanna': 'Dan',
'Josue': 'Josh',
'Ecclesiasticus': 'Sir',
'Esther': 'Esther',
'2 Thessalonian': '2 Thess',
'Luke': 'Lk',
'2 Thessalonians': '2 Thess',
'Judith': 'Jud',
'1 Chronicles': '1 Chron',
'1 Timothy': '1 Tim',
'Joel': 'Joel',
'2 Chronicles': '2 Chron',
'Nehemiah': 'Neh',
'1 John': '1 Jn',
'1 Peter': '1 Pet',
'1 Samuel': '1 Sam',
'1 Corinthians': '1 Cor',
'Zacharias': 'Zech',
'Additions to the Book of Esther': '2 Esther',
'2 Kings': '2 Sam',
'Ecclesiastes': 'Eccles'}
