// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_TranslationBuffer_2eproto__INCLUDED
#define PROTOBUF_TranslationBuffer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>

namespace BibleDatabase {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TranslationBuffer_2eproto();
void protobuf_AssignDesc_TranslationBuffer_2eproto();
void protobuf_ShutdownFile_TranslationBuffer_2eproto();

class VerseBuffer;
class TranslationBuffer;

// ===================================================================

class VerseBuffer : public ::google::protobuf::Message {
 public:
  VerseBuffer();
  virtual ~VerseBuffer();
  
  VerseBuffer(const VerseBuffer& from);
  
  inline VerseBuffer& operator=(const VerseBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const VerseBuffer& default_instance();
  void Swap(VerseBuffer* other);
  
  // implements Message ----------------------------------------------
  
  VerseBuffer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VerseBuffer& from);
  void MergeFrom(const VerseBuffer& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string book = 1;
  inline bool has_book() const;
  inline void clear_book();
  static const int kBookFieldNumber = 1;
  inline const ::std::string& book() const;
  inline void set_book(const ::std::string& value);
  inline void set_book(const char* value);
  inline void set_book(const char* value, size_t size);
  inline ::std::string* mutable_book();
  
  // required int32 chapter = 2;
  inline bool has_chapter() const;
  inline void clear_chapter();
  static const int kChapterFieldNumber = 2;
  inline ::google::protobuf::int32 chapter() const;
  inline void set_chapter(::google::protobuf::int32 value);
  
  // required int32 verse = 3;
  inline bool has_verse() const;
  inline void clear_verse();
  static const int kVerseFieldNumber = 3;
  inline ::google::protobuf::int32 verse() const;
  inline void set_verse(::google::protobuf::int32 value);
  
  // required string text = 4;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 4;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const char* value, size_t size);
  inline ::std::string* mutable_text();
  
  // required int32 unique_id = 5;
  inline bool has_unique_id() const;
  inline void clear_unique_id();
  static const int kUniqueIdFieldNumber = 5;
  inline ::google::protobuf::int32 unique_id() const;
  inline void set_unique_id(::google::protobuf::int32 value);
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* book_;
  static const ::std::string _default_book_;
  ::google::protobuf::int32 chapter_;
  ::google::protobuf::int32 verse_;
  ::std::string* text_;
  static const ::std::string _default_text_;
  ::google::protobuf::int32 unique_id_;
  friend void  protobuf_AddDesc_TranslationBuffer_2eproto();
  friend void protobuf_AssignDesc_TranslationBuffer_2eproto();
  friend void protobuf_ShutdownFile_TranslationBuffer_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static VerseBuffer* default_instance_;
};
// -------------------------------------------------------------------

class TranslationBuffer : public ::google::protobuf::Message {
 public:
  TranslationBuffer();
  virtual ~TranslationBuffer();
  
  TranslationBuffer(const TranslationBuffer& from);
  
  inline TranslationBuffer& operator=(const TranslationBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TranslationBuffer& default_instance();
  void Swap(TranslationBuffer* other);
  
  // implements Message ----------------------------------------------
  
  TranslationBuffer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TranslationBuffer& from);
  void MergeFrom(const TranslationBuffer& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string long_name = 1;
  inline bool has_long_name() const;
  inline void clear_long_name();
  static const int kLongNameFieldNumber = 1;
  inline const ::std::string& long_name() const;
  inline void set_long_name(const ::std::string& value);
  inline void set_long_name(const char* value);
  inline void set_long_name(const char* value, size_t size);
  inline ::std::string* mutable_long_name();
  
  // required string short_name = 2;
  inline bool has_short_name() const;
  inline void clear_short_name();
  static const int kShortNameFieldNumber = 2;
  inline const ::std::string& short_name() const;
  inline void set_short_name(const ::std::string& value);
  inline void set_short_name(const char* value);
  inline void set_short_name(const char* value, size_t size);
  inline ::std::string* mutable_short_name();
  
  // repeated .BibleDatabase.VerseBuffer verse = 3;
  inline int verse_size() const;
  inline void clear_verse();
  static const int kVerseFieldNumber = 3;
  inline const ::google::protobuf::RepeatedPtrField< ::BibleDatabase::VerseBuffer >& verse() const;
  inline ::google::protobuf::RepeatedPtrField< ::BibleDatabase::VerseBuffer >* mutable_verse();
  inline const ::BibleDatabase::VerseBuffer& verse(int index) const;
  inline ::BibleDatabase::VerseBuffer* mutable_verse(int index);
  inline ::BibleDatabase::VerseBuffer* add_verse();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* long_name_;
  static const ::std::string _default_long_name_;
  ::std::string* short_name_;
  static const ::std::string _default_short_name_;
  ::google::protobuf::RepeatedPtrField< ::BibleDatabase::VerseBuffer > verse_;
  friend void  protobuf_AddDesc_TranslationBuffer_2eproto();
  friend void protobuf_AssignDesc_TranslationBuffer_2eproto();
  friend void protobuf_ShutdownFile_TranslationBuffer_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static TranslationBuffer* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// VerseBuffer

// required string book = 1;
inline bool VerseBuffer::has_book() const {
  return _has_bit(0);
}
inline void VerseBuffer::clear_book() {
  if (book_ != &_default_book_) {
    book_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& VerseBuffer::book() const {
  return *book_;
}
inline void VerseBuffer::set_book(const ::std::string& value) {
  _set_bit(0);
  if (book_ == &_default_book_) {
    book_ = new ::std::string;
  }
  book_->assign(value);
}
inline void VerseBuffer::set_book(const char* value) {
  _set_bit(0);
  if (book_ == &_default_book_) {
    book_ = new ::std::string;
  }
  book_->assign(value);
}
inline void VerseBuffer::set_book(const char* value, size_t size) {
  _set_bit(0);
  if (book_ == &_default_book_) {
    book_ = new ::std::string;
  }
  book_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* VerseBuffer::mutable_book() {
  _set_bit(0);
  if (book_ == &_default_book_) {
    book_ = new ::std::string;
  }
  return book_;
}

// required int32 chapter = 2;
inline bool VerseBuffer::has_chapter() const {
  return _has_bit(1);
}
inline void VerseBuffer::clear_chapter() {
  chapter_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 VerseBuffer::chapter() const {
  return chapter_;
}
inline void VerseBuffer::set_chapter(::google::protobuf::int32 value) {
  _set_bit(1);
  chapter_ = value;
}

// required int32 verse = 3;
inline bool VerseBuffer::has_verse() const {
  return _has_bit(2);
}
inline void VerseBuffer::clear_verse() {
  verse_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 VerseBuffer::verse() const {
  return verse_;
}
inline void VerseBuffer::set_verse(::google::protobuf::int32 value) {
  _set_bit(2);
  verse_ = value;
}

// required string text = 4;
inline bool VerseBuffer::has_text() const {
  return _has_bit(3);
}
inline void VerseBuffer::clear_text() {
  if (text_ != &_default_text_) {
    text_->clear();
  }
  _clear_bit(3);
}
inline const ::std::string& VerseBuffer::text() const {
  return *text_;
}
inline void VerseBuffer::set_text(const ::std::string& value) {
  _set_bit(3);
  if (text_ == &_default_text_) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void VerseBuffer::set_text(const char* value) {
  _set_bit(3);
  if (text_ == &_default_text_) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void VerseBuffer::set_text(const char* value, size_t size) {
  _set_bit(3);
  if (text_ == &_default_text_) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* VerseBuffer::mutable_text() {
  _set_bit(3);
  if (text_ == &_default_text_) {
    text_ = new ::std::string;
  }
  return text_;
}

// required int32 unique_id = 5;
inline bool VerseBuffer::has_unique_id() const {
  return _has_bit(4);
}
inline void VerseBuffer::clear_unique_id() {
  unique_id_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 VerseBuffer::unique_id() const {
  return unique_id_;
}
inline void VerseBuffer::set_unique_id(::google::protobuf::int32 value) {
  _set_bit(4);
  unique_id_ = value;
}

// -------------------------------------------------------------------

// TranslationBuffer

// required string long_name = 1;
inline bool TranslationBuffer::has_long_name() const {
  return _has_bit(0);
}
inline void TranslationBuffer::clear_long_name() {
  if (long_name_ != &_default_long_name_) {
    long_name_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& TranslationBuffer::long_name() const {
  return *long_name_;
}
inline void TranslationBuffer::set_long_name(const ::std::string& value) {
  _set_bit(0);
  if (long_name_ == &_default_long_name_) {
    long_name_ = new ::std::string;
  }
  long_name_->assign(value);
}
inline void TranslationBuffer::set_long_name(const char* value) {
  _set_bit(0);
  if (long_name_ == &_default_long_name_) {
    long_name_ = new ::std::string;
  }
  long_name_->assign(value);
}
inline void TranslationBuffer::set_long_name(const char* value, size_t size) {
  _set_bit(0);
  if (long_name_ == &_default_long_name_) {
    long_name_ = new ::std::string;
  }
  long_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TranslationBuffer::mutable_long_name() {
  _set_bit(0);
  if (long_name_ == &_default_long_name_) {
    long_name_ = new ::std::string;
  }
  return long_name_;
}

// required string short_name = 2;
inline bool TranslationBuffer::has_short_name() const {
  return _has_bit(1);
}
inline void TranslationBuffer::clear_short_name() {
  if (short_name_ != &_default_short_name_) {
    short_name_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& TranslationBuffer::short_name() const {
  return *short_name_;
}
inline void TranslationBuffer::set_short_name(const ::std::string& value) {
  _set_bit(1);
  if (short_name_ == &_default_short_name_) {
    short_name_ = new ::std::string;
  }
  short_name_->assign(value);
}
inline void TranslationBuffer::set_short_name(const char* value) {
  _set_bit(1);
  if (short_name_ == &_default_short_name_) {
    short_name_ = new ::std::string;
  }
  short_name_->assign(value);
}
inline void TranslationBuffer::set_short_name(const char* value, size_t size) {
  _set_bit(1);
  if (short_name_ == &_default_short_name_) {
    short_name_ = new ::std::string;
  }
  short_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TranslationBuffer::mutable_short_name() {
  _set_bit(1);
  if (short_name_ == &_default_short_name_) {
    short_name_ = new ::std::string;
  }
  return short_name_;
}

// repeated .BibleDatabase.VerseBuffer verse = 3;
inline int TranslationBuffer::verse_size() const {
  return verse_.size();
}
inline void TranslationBuffer::clear_verse() {
  verse_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::BibleDatabase::VerseBuffer >&
TranslationBuffer::verse() const {
  return verse_;
}
inline ::google::protobuf::RepeatedPtrField< ::BibleDatabase::VerseBuffer >*
TranslationBuffer::mutable_verse() {
  return &verse_;
}
inline const ::BibleDatabase::VerseBuffer& TranslationBuffer::verse(int index) const {
  return verse_.Get(index);
}
inline ::BibleDatabase::VerseBuffer* TranslationBuffer::mutable_verse(int index) {
  return verse_.Mutable(index);
}
inline ::BibleDatabase::VerseBuffer* TranslationBuffer::add_verse() {
  return verse_.Add();
}


}  // namespace BibleDatabase

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

#endif  // PROTOBUF_TranslationBuffer_2eproto__INCLUDED
